name = "CarouselGreedy"
uuid = "100727de-7a56-4b5d-9379-46eb10e23cf1"
authors = ["Raffaele Dragone <raffaele.dragone@edu.unige.it>"]
version = "0.1.3"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.9"